//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP_Organizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP_Organizer.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Calculator_Armor {
            get {
                return ResourceManager.GetString("Calculator_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Mode.
        /// </summary>
        public static string Calculator_AttackMode {
            get {
                return ResourceManager.GetString("Calculator_AttackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Damage.
        /// </summary>
        public static string Calculator_BaseDamage {
            get {
                return ResourceManager.GetString("Calculator_BaseDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Damage Multiplier.
        /// </summary>
        public static string Calculator_BaseDamageMultiplier {
            get {
                return ResourceManager.GetString("Calculator_BaseDamageMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculator_Calculate {
            get {
                return ResourceManager.GetString("Calculator_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Calculator_Damage {
            get {
                return ResourceManager.GetString("Calculator_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge / Parry.
        /// </summary>
        public static string Calculator_DodgeParry {
            get {
                return ResourceManager.GetString("Calculator_DodgeParry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Damage Multiplier.
        /// </summary>
        public static string Calculator_EndDamageMultiplier {
            get {
                return ResourceManager.GetString("Calculator_EndDamageMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string Calculator_Hit {
            get {
                return ResourceManager.GetString("Calculator_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Calculator_Melee {
            get {
                return ResourceManager.GetString("Calculator_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Calculator_Modifiers {
            get {
                return ResourceManager.GetString("Calculator_Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Calculator_Ranged {
            get {
                return ResourceManager.GetString("Calculator_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Container_MenuEdit {
            get {
                return ResourceManager.GetString("Container_MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Container_MenuExit {
            get {
                return ResourceManager.GetString("Container_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Container_MenuFile {
            get {
                return ResourceManager.GetString("Container_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character.
        /// </summary>
        public static string Container_MenuNew {
            get {
                return ResourceManager.GetString("Container_MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Container_MenuOpen {
            get {
                return ResourceManager.GetString("Container_MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Container_MenuSave {
            get {
                return ResourceManager.GetString("Container_MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Container_MenuSaveAs {
            get {
                return ResourceManager.GetString("Container_MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Container_MenuSettings {
            get {
                return ResourceManager.GetString("Container_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Container_NavigationCalculator {
            get {
                return ResourceManager.GetString("Container_NavigationCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Container_NavigationDashboard {
            get {
                return ResourceManager.GetString("Container_NavigationDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Container_NavigationInventory {
            get {
                return ResourceManager.GetString("Container_NavigationInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Container_NavigationNotes {
            get {
                return ResourceManager.GetString("Container_NavigationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Container_NavigationOverview {
            get {
                return ResourceManager.GetString("Container_NavigationOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Container_NavigationSettings {
            get {
                return ResourceManager.GetString("Container_NavigationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Container_NavigationSkills {
            get {
                return ResourceManager.GetString("Container_NavigationSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Character.
        /// </summary>
        public static string Dashboard_TooltipLoadCharacter {
            get {
                return ResourceManager.GetString("Dashboard_TooltipLoadCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character.
        /// </summary>
        public static string Dashboard_TooltipNewCharacter {
            get {
                return ResourceManager.GetString("Dashboard_TooltipNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back!.
        /// </summary>
        public static string Dashboard_WelcomeMessage {
            get {
                return ResourceManager.GetString("Dashboard_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Global_CopyToClipboard {
            get {
                return ResourceManager.GetString("Global_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add Image.
        /// </summary>
        public static string Global_TooltipAddImage {
            get {
                return ResourceManager.GetString("Global_TooltipAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Inventory_PlaceholderDescription {
            get {
                return ResourceManager.GetString("Inventory_PlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Inventory_PlaceholderName {
            get {
                return ResourceManager.GetString("Inventory_PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Inventory_TooltipAddItem {
            get {
                return ResourceManager.GetString("Inventory_TooltipAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Color.
        /// </summary>
        public static string Inventory_TooltipChangeColor {
            get {
                return ResourceManager.GetString("Inventory_TooltipChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Item.
        /// </summary>
        public static string Inventory_TooltipClearItem {
            get {
                return ResourceManager.GetString("Inventory_TooltipClearItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string Inventory_TooltipDeleteItem {
            get {
                return ResourceManager.GetString("Inventory_TooltipDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Overview_Age {
            get {
                return ResourceManager.GetString("Overview_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Overview_AttrCharisma {
            get {
                return ResourceManager.GetString("Overview_AttrCharisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitutions.
        /// </summary>
        public static string Overview_AttrConstitution {
            get {
                return ResourceManager.GetString("Overview_AttrConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string Overview_AttrDexterity {
            get {
                return ResourceManager.GetString("Overview_AttrDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Overview_Attributes {
            get {
                return ResourceManager.GetString("Overview_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Overview_AttrIntelligence {
            get {
                return ResourceManager.GetString("Overview_AttrIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Overview_AttrStrength {
            get {
                return ResourceManager.GetString("Overview_AttrStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string Overview_AttrWisdom {
            get {
                return ResourceManager.GetString("Overview_AttrWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Overview_Energy {
            get {
                return ResourceManager.GetString("Overview_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Overview_Health {
            get {
                return ResourceManager.GetString("Overview_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Overview_Height {
            get {
                return ResourceManager.GetString("Overview_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        public static string Overview_Initiative {
            get {
                return ResourceManager.GetString("Overview_Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Overview_Name {
            get {
                return ResourceManager.GetString("Overview_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearls.
        /// </summary>
        public static string Overview_Pearls {
            get {
                return ResourceManager.GetString("Overview_Pearls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string Overview_PearlsAir {
            get {
                return ResourceManager.GetString("Overview_PearlsAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Overview_PearlsEarth {
            get {
                return ResourceManager.GetString("Overview_PearlsEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Overview_PearlsFire {
            get {
                return ResourceManager.GetString("Overview_PearlsFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Overview_PearlsMetal {
            get {
                return ResourceManager.GetString("Overview_PearlsMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Overview_PearlsWater {
            get {
                return ResourceManager.GetString("Overview_PearlsWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Overview_PearlsWood {
            get {
                return ResourceManager.GetString("Overview_PearlsWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string Overview_Stamina {
            get {
                return ResourceManager.GetString("Overview_Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PnP-Organizer.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Calculations.
        /// </summary>
        public static string Settings_LogCalculations {
            get {
                return ResourceManager.GetString("Settings_LogCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Logfiles.
        /// </summary>
        public static string Settings_MaximumLogfiles {
            get {
                return ResourceManager.GetString("Settings_MaximumLogfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Skills_All {
            get {
                return ResourceManager.GetString("Skills_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Skills_Character {
            get {
                return ResourceManager.GetString("Skills_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Skills_Filter {
            get {
                return ResourceManager.GetString("Skills_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Skills_Melee {
            get {
                return ResourceManager.GetString("Skills_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Skills_Ranged {
            get {
                return ResourceManager.GetString("Skills_Ranged", resourceCulture);
            }
        }
    }
}
