//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnP_Organizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PnP_Organizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobatic.
        /// </summary>
        public static string AttributeTests_Acrobatic {
            get {
                return ResourceManager.GetString("AttributeTests_Acrobatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletic.
        /// </summary>
        public static string AttributeTests_Athletic {
            get {
                return ResourceManager.GetString("AttributeTests_Athletic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluff.
        /// </summary>
        public static string AttributeTests_Bluff {
            get {
                return ResourceManager.GetString("AttributeTests_Bluff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string AttributeTests_Filter {
            get {
                return ResourceManager.GetString("AttributeTests_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-Aid.
        /// </summary>
        public static string AttributeTests_FirstAid {
            get {
                return ResourceManager.GetString("AttributeTests_FirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Animals.
        /// </summary>
        public static string AttributeTests_HandleAnimals {
            get {
                return ResourceManager.GetString("AttributeTests_HandleAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string AttributeTests_History {
            get {
                return ResourceManager.GetString("AttributeTests_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string AttributeTests_Insight {
            get {
                return ResourceManager.GetString("AttributeTests_Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string AttributeTests_Inspect {
            get {
                return ResourceManager.GetString("AttributeTests_Inspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidate.
        /// </summary>
        public static string AttributeTests_Intimidate {
            get {
                return ResourceManager.GetString("AttributeTests_Intimidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string AttributeTests_Nature {
            get {
                return ResourceManager.GetString("AttributeTests_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string AttributeTests_OrderBy {
            get {
                return ResourceManager.GetString("AttributeTests_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perceive.
        /// </summary>
        public static string AttributeTests_Perceive {
            get {
                return ResourceManager.GetString("AttributeTests_Perceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string AttributeTests_Performance {
            get {
                return ResourceManager.GetString("AttributeTests_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persuade.
        /// </summary>
        public static string AttributeTests_Persuade {
            get {
                return ResourceManager.GetString("AttributeTests_Persuade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physique.
        /// </summary>
        public static string AttributeTests_Physique {
            get {
                return ResourceManager.GetString("AttributeTests_Physique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleight of Hand.
        /// </summary>
        public static string AttributeTests_SleightOfHand {
            get {
                return ResourceManager.GetString("AttributeTests_SleightOfHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak / Hide.
        /// </summary>
        public static string AttributeTests_SneakHide {
            get {
                return ResourceManager.GetString("AttributeTests_SneakHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professions.
        /// </summary>
        public static string AttributeTests_TitleProfessions {
            get {
                return ResourceManager.GetString("AttributeTests_TitleProfessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string AttributeTests_TitleTests {
            get {
                return ResourceManager.GetString("AttributeTests_TitleTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cha.
        /// </summary>
        public static string AttributeTests_TypeCharisma {
            get {
                return ResourceManager.GetString("AttributeTests_TypeCharisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con.
        /// </summary>
        public static string AttributeTests_TypeConstitution {
            get {
                return ResourceManager.GetString("AttributeTests_TypeConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dex.
        /// </summary>
        public static string AttributeTests_TypeDexterity {
            get {
                return ResourceManager.GetString("AttributeTests_TypeDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        public static string AttributeTests_TypeIntelligence {
            get {
                return ResourceManager.GetString("AttributeTests_TypeIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Str.
        /// </summary>
        public static string AttributeTests_TypeStrength {
            get {
                return ResourceManager.GetString("AttributeTests_TypeStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wis.
        /// </summary>
        public static string AttributeTests_TypeWisdom {
            get {
                return ResourceManager.GetString("AttributeTests_TypeWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Calculator_Armor {
            get {
                return ResourceManager.GetString("Calculator_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Mode.
        /// </summary>
        public static string Calculator_AttackMode {
            get {
                return ResourceManager.GetString("Calculator_AttackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Armor.
        /// </summary>
        public static string Calculator_BaseArmor {
            get {
                return ResourceManager.GetString("Calculator_BaseArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Damage.
        /// </summary>
        public static string Calculator_BaseDamage {
            get {
                return ResourceManager.GetString("Calculator_BaseDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Damage Multiplier.
        /// </summary>
        public static string Calculator_BaseDamageMultiplier {
            get {
                return ResourceManager.GetString("Calculator_BaseDamageMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculator_Calculate {
            get {
                return ResourceManager.GetString("Calculator_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Calculator_Damage {
            get {
                return ResourceManager.GetString("Calculator_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge / Parry.
        /// </summary>
        public static string Calculator_DodgeParry {
            get {
                return ResourceManager.GetString("Calculator_DodgeParry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Damage Multiplier.
        /// </summary>
        public static string Calculator_EndDamageMultiplier {
            get {
                return ResourceManager.GetString("Calculator_EndDamageMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string Calculator_Hit {
            get {
                return ResourceManager.GetString("Calculator_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Calculator_Melee {
            get {
                return ResourceManager.GetString("Calculator_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Calculator_Modifiers {
            get {
                return ResourceManager.GetString("Calculator_Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Calculator_Ranged {
            get {
                return ResourceManager.GetString("Calculator_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Container_MenuEdit {
            get {
                return ResourceManager.GetString("Container_MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Container_MenuExit {
            get {
                return ResourceManager.GetString("Container_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Container_MenuFile {
            get {
                return ResourceManager.GetString("Container_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character.
        /// </summary>
        public static string Container_MenuNew {
            get {
                return ResourceManager.GetString("Container_MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Container_MenuOpen {
            get {
                return ResourceManager.GetString("Container_MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Container_MenuSave {
            get {
                return ResourceManager.GetString("Container_MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Container_MenuSaveAs {
            get {
                return ResourceManager.GetString("Container_MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Container_MenuSettings {
            get {
                return ResourceManager.GetString("Container_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Tests.
        /// </summary>
        public static string Container_NavigationAttributeTests {
            get {
                return ResourceManager.GetString("Container_NavigationAttributeTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Container_NavigationCalculator {
            get {
                return ResourceManager.GetString("Container_NavigationCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Container_NavigationDashboard {
            get {
                return ResourceManager.GetString("Container_NavigationDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Container_NavigationInventory {
            get {
                return ResourceManager.GetString("Container_NavigationInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Container_NavigationNotes {
            get {
                return ResourceManager.GetString("Container_NavigationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Container_NavigationOverview {
            get {
                return ResourceManager.GetString("Container_NavigationOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Container_NavigationSettings {
            get {
                return ResourceManager.GetString("Container_NavigationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Container_NavigationSkills {
            get {
                return ResourceManager.GetString("Container_NavigationSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Character.
        /// </summary>
        public static string Dashboard_TooltipLoadCharacter {
            get {
                return ResourceManager.GetString("Dashboard_TooltipLoadCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character.
        /// </summary>
        public static string Dashboard_TooltipNewCharacter {
            get {
                return ResourceManager.GetString("Dashboard_TooltipNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back!.
        /// </summary>
        public static string Dashboard_WelcomeMessage {
            get {
                return ResourceManager.GetString("Dashboard_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_ButtonCancel {
            get {
                return ResourceManager.GetString("Dialog_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Dialog_ButtonClear {
            get {
                return ResourceManager.GetString("Dialog_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Dialog_ButtonDelete {
            get {
                return ResourceManager.GetString("Dialog_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string Dialog_ButtonDiscardChanges {
            get {
                return ResourceManager.GetString("Dialog_ButtonDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Dialog_ButtonNo {
            get {
                return ResourceManager.GetString("Dialog_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Dialog_ButtonSaveChanges {
            get {
                return ResourceManager.GetString("Dialog_ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Dialog_ButtonYes {
            get {
                return ResourceManager.GetString("Dialog_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear this Item?.
        /// </summary>
        public static string Dialog_ItemClearingMessage {
            get {
                return ResourceManager.GetString("Dialog_ItemClearingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Item Clearing.
        /// </summary>
        public static string Dialog_ItemClearingTitle {
            get {
                return ResourceManager.GetString("Dialog_ItemClearingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Item?.
        /// </summary>
        public static string Dialog_ItemDeletionMessage {
            get {
                return ResourceManager.GetString("Dialog_ItemDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Item Deletion.
        /// </summary>
        public static string Dialog_ItemDeletionTitle {
            get {
                return ResourceManager.GetString("Dialog_ItemDeletionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Character.
        /// </summary>
        public static string Dialog_NewCharacterTitle {
            get {
                return ResourceManager.GetString("Dialog_NewCharacterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Character.
        /// </summary>
        public static string Dialog_OpenCharacterTitle {
            get {
                return ResourceManager.GetString("Dialog_OpenCharacterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        public static string Dialog_OpenImage {
            get {
                return ResourceManager.GetString("Dialog_OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the last saved Character?.
        /// </summary>
        public static string Dialog_OpenLastCharacterMessage {
            get {
                return ResourceManager.GetString("Dialog_OpenLastCharacterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open last Character.
        /// </summary>
        public static string Dialog_OpenLastCharacterTitle {
            get {
                return ResourceManager.GetString("Dialog_OpenLastCharacterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Character.
        /// </summary>
        public static string Dialog_SaveCharacterTitle {
            get {
                return ResourceManager.GetString("Dialog_SaveCharacterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes! Do you want to save the Character before closing?.
        /// </summary>
        public static string Dialog_UnsavedCharacterCloseMessage {
            get {
                return ResourceManager.GetString("Dialog_UnsavedCharacterCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Character changes.
        /// </summary>
        public static string Dialog_UnsavedCharacterCloseTitle {
            get {
                return ResourceManager.GetString("Dialog_UnsavedCharacterCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you still want to create a new Character?.
        /// </summary>
        public static string Dialog_UnsavedCharacterNewMessage {
            get {
                return ResourceManager.GetString("Dialog_UnsavedCharacterNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you want to save before loading a different Character?.
        /// </summary>
        public static string Dialog_UnsavedCharacterOpenMessage {
            get {
                return ResourceManager.GetString("Dialog_UnsavedCharacterOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Inventory_PlaceholderDescription {
            get {
                return ResourceManager.GetString("Inventory_PlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Inventory_PlaceholderName {
            get {
                return ResourceManager.GetString("Inventory_PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Item....
        /// </summary>
        public static string Inventory_SearchItemPlaceholder {
            get {
                return ResourceManager.GetString("Inventory_SearchItemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Inventory_TooltipAddItem {
            get {
                return ResourceManager.GetString("Inventory_TooltipAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Color.
        /// </summary>
        public static string Inventory_TooltipChangeColor {
            get {
                return ResourceManager.GetString("Inventory_TooltipChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Item.
        /// </summary>
        public static string Inventory_TooltipClearItem {
            get {
                return ResourceManager.GetString("Inventory_TooltipClearItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string Inventory_TooltipDeleteItem {
            get {
                return ResourceManager.GetString("Inventory_TooltipDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Overview_Age {
            get {
                return ResourceManager.GetString("Overview_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Overview_AttrCharisma {
            get {
                return ResourceManager.GetString("Overview_AttrCharisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitutions.
        /// </summary>
        public static string Overview_AttrConstitution {
            get {
                return ResourceManager.GetString("Overview_AttrConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string Overview_AttrDexterity {
            get {
                return ResourceManager.GetString("Overview_AttrDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Overview_Attributes {
            get {
                return ResourceManager.GetString("Overview_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Overview_AttrIntelligence {
            get {
                return ResourceManager.GetString("Overview_AttrIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Overview_AttrStrength {
            get {
                return ResourceManager.GetString("Overview_AttrStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string Overview_AttrWisdom {
            get {
                return ResourceManager.GetString("Overview_AttrWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Overview_Energy {
            get {
                return ResourceManager.GetString("Overview_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Overview_Health {
            get {
                return ResourceManager.GetString("Overview_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Overview_Height {
            get {
                return ResourceManager.GetString("Overview_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        public static string Overview_Initiative {
            get {
                return ResourceManager.GetString("Overview_Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Overview_Name {
            get {
                return ResourceManager.GetString("Overview_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearls.
        /// </summary>
        public static string Overview_Pearls {
            get {
                return ResourceManager.GetString("Overview_Pearls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        public static string Overview_PearlsAir {
            get {
                return ResourceManager.GetString("Overview_PearlsAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Overview_PearlsEarth {
            get {
                return ResourceManager.GetString("Overview_PearlsEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Overview_PearlsFire {
            get {
                return ResourceManager.GetString("Overview_PearlsFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Overview_PearlsMetal {
            get {
                return ResourceManager.GetString("Overview_PearlsMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Overview_PearlsWater {
            get {
                return ResourceManager.GetString("Overview_PearlsWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Overview_PearlsWood {
            get {
                return ResourceManager.GetString("Overview_PearlsWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string Overview_Stamina {
            get {
                return ResourceManager.GetString("Overview_Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PnP-Organizer.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Calculations.
        /// </summary>
        public static string Settings_LogCalculations {
            get {
                return ResourceManager.GetString("Settings_LogCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Logfiles.
        /// </summary>
        public static string Settings_MaximumLogfiles {
            get {
                return ResourceManager.GetString("Settings_MaximumLogfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Open last saved Character&quot; dialog.
        /// </summary>
        public static string Settings_OpenLastCharacterDialogEnable {
            get {
                return ResourceManager.GetString("Settings_OpenLastCharacterDialogEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning Blade.
        /// </summary>
        public static string Skill_BurningBlade {
            get {
                return ResourceManager.GetString("Skill_BurningBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 1 * Fire pearls damage.
        /// </summary>
        public static string Skill_BurningBladeDescription {
            get {
                return ResourceManager.GetString("Skill_BurningBladeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Furycraft Bow.
        /// </summary>
        public static string Skill_EarthBow {
            get {
                return ResourceManager.GetString("Skill_EarthBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 1 * Earth pearls damage.
        /// </summary>
        public static string Skill_EarthBowDescription {
            get {
                return ResourceManager.GetString("Skill_EarthBowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Furycraft Active.
        /// </summary>
        public static string Skill_MetalActive {
            get {
                return ResourceManager.GetString("Skill_MetalActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + 1 * Metal pearls damage.
        /// </summary>
        public static string Skill_MetalActiveDescription {
            get {
                return ResourceManager.GetString("Skill_MetalActiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Ground.
        /// </summary>
        public static string Skill_OnGround {
            get {
                return ResourceManager.GetString("Skill_OnGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 * Earth pearls damage.
        /// </summary>
        public static string Skill_OnGroundDescription {
            get {
                return ResourceManager.GetString("Skill_OnGroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeded.
        /// </summary>
        public static string Skill_Speeded {
            get {
                return ResourceManager.GetString("Skill_Speeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 * Air pearls damage, parry and dodge
        ///+0.5 * Air pearls incoming damage.
        /// </summary>
        public static string Skill_SpeededDescription {
            get {
                return ResourceManager.GetString("Skill_SpeededDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Profession.
        /// </summary>
        public static string Skill_WeaponProfession {
            get {
                return ResourceManager.GetString("Skill_WeaponProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 Damage.
        /// </summary>
        public static string Skill_WeaponProfessionDescription {
            get {
                return ResourceManager.GetString("Skill_WeaponProfessionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Skills_All {
            get {
                return ResourceManager.GetString("Skills_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Skills_Character {
            get {
                return ResourceManager.GetString("Skills_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Skills_Filter {
            get {
                return ResourceManager.GetString("Skills_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Skills_Locked {
            get {
                return ResourceManager.GetString("Skills_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Skills_Melee {
            get {
                return ResourceManager.GetString("Skills_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Skills_Ranged {
            get {
                return ResourceManager.GetString("Skills_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Skill....
        /// </summary>
        public static string Skills_SearchSkillPlaceholder {
            get {
                return ResourceManager.GetString("Skills_SearchSkillPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillability.
        /// </summary>
        public static string Skills_Skillability {
            get {
                return ResourceManager.GetString("Skills_Skillability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillable.
        /// </summary>
        public static string Skills_Skillable {
            get {
                return ResourceManager.GetString("Skills_Skillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate.
        /// </summary>
        public static string Skills_SkillAccurateMelee {
            get {
                return ResourceManager.GetString("Skills_SkillAccurateMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate.
        /// </summary>
        public static string Skills_SkillAccurateRanged {
            get {
                return ResourceManager.GetString("Skills_SkillAccurateRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor by Birth.
        /// </summary>
        public static string Skills_SkillActorByBirth {
            get {
                return ResourceManager.GetString("Skills_SkillActorByBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agressive Fighting.
        /// </summary>
        public static string Skills_SkillAgressiveFighting {
            get {
                return ResourceManager.GetString("Skills_SkillAgressiveFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aimed Attack.
        /// </summary>
        public static string Skills_SkillAimedAttackMelee {
            get {
                return ResourceManager.GetString("Skills_SkillAimedAttackMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aimed Attack.
        /// </summary>
        public static string Skills_SkillAimedAttackRanged {
            get {
                return ResourceManager.GetString("Skills_SkillAimedAttackRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertness.
        /// </summary>
        public static string Skills_SkillAlertness {
            get {
                return ResourceManager.GetString("Skills_SkillAlertness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Skills_SkillArmor {
            get {
                return ResourceManager.GetString("Skills_SkillArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Breaker.
        /// </summary>
        public static string Skills_SkillArmorBreaker {
            get {
                return ResourceManager.GetString("Skills_SkillArmorBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Up.
        /// </summary>
        public static string Skills_SkillArmorUp {
            get {
                return ResourceManager.GetString("Skills_SkillArmorUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassinate.
        /// </summary>
        public static string Skills_SkillAssassinate {
            get {
                return ResourceManager.GetString("Skills_SkillAssassinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack of Opportunity.
        /// </summary>
        public static string Skills_SkillAttackOfOpportunity {
            get {
                return ResourceManager.GetString("Skills_SkillAttackOfOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenger.
        /// </summary>
        public static string Skills_SkillAvenger {
            get {
                return ResourceManager.GetString("Skills_SkillAvenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backline.
        /// </summary>
        public static string Skills_SkillBackLine {
            get {
                return ResourceManager.GetString("Skills_SkillBackLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better than Throwing.
        /// </summary>
        public static string Skills_SkillBetterThanThrowing {
            get {
                return ResourceManager.GetString("Skills_SkillBetterThanThrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Fan.
        /// </summary>
        public static string Skills_SkillBladeFan {
            get {
                return ResourceManager.GetString("Skills_SkillBladeFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow Making.
        /// </summary>
        public static string Skills_SkillBowMaking {
            get {
                return ResourceManager.GetString("Skills_SkillBowMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Arrows.
        /// </summary>
        public static string Skills_SkillBuildArrows {
            get {
                return ResourceManager.GetString("Skills_SkillBuildArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calm Aiming.
        /// </summary>
        public static string Skills_SkillCalmAiming {
            get {
                return ResourceManager.GetString("Skills_SkillCalmAiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavallery.
        /// </summary>
        public static string Skills_SkillCavallery {
            get {
                return ResourceManager.GetString("Skills_SkillCavallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Attack.
        /// </summary>
        public static string Skills_SkillChainAttack {
            get {
                return ResourceManager.GetString("Skills_SkillChainAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climbing.
        /// </summary>
        public static string Skills_SkillClimbing {
            get {
                return ResourceManager.GetString("Skills_SkillClimbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        public static string Skills_SkillCombo {
            get {
                return ResourceManager.GetString("Skills_SkillCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Tone.
        /// </summary>
        public static string Skills_SkillCommandTone {
            get {
                return ResourceManager.GetString("Skills_SkillCommandTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterfeiting.
        /// </summary>
        public static string Skills_SkillCounterfeiting {
            get {
                return ResourceManager.GetString("Skills_SkillCounterfeiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crippling Blow.
        /// </summary>
        public static string Skills_SkillCripplingBlow {
            get {
                return ResourceManager.GetString("Skills_SkillCripplingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Shot.
        /// </summary>
        public static string Skills_SkillCurvedShot {
            get {
                return ResourceManager.GetString("Skills_SkillCurvedShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive Fighting.
        /// </summary>
        public static string Skills_SkillDefensiveFighting {
            get {
                return ResourceManager.GetString("Skills_SkillDefensiveFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive Stance.
        /// </summary>
        public static string Skills_SkillDefensiveStance {
            get {
                return ResourceManager.GetString("Skills_SkillDefensiveStance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devastating Attack.
        /// </summary>
        public static string Skills_SkillDevastatingAttack {
            get {
                return ResourceManager.GetString("Skills_SkillDevastatingAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarm.
        /// </summary>
        public static string Skills_SkillDisarmMelee {
            get {
                return ResourceManager.GetString("Skills_SkillDisarmMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarm.
        /// </summary>
        public static string Skills_SkillDisarmRanged {
            get {
                return ResourceManager.GetString("Skills_SkillDisarmRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubleshot.
        /// </summary>
        public static string Skills_SkillDoubleShot {
            get {
                return ResourceManager.GetString("Skills_SkillDoubleShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Throw.
        /// </summary>
        public static string Skills_SkillDualThrow {
            get {
                return ResourceManager.GetString("Skills_SkillDualThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex Ferrum.
        /// </summary>
        public static string Skills_SkillDuplexFerrum {
            get {
                return ResourceManager.GetString("Skills_SkillDuplexFerrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled.
        /// </summary>
        public static string Skills_Skilled {
            get {
                return ResourceManager.GetString("Skills_Skilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encouragement.
        /// </summary>
        public static string Skills_SkillEncouragement {
            get {
                return ResourceManager.GetString("Skills_SkillEncouragement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Boost.
        /// </summary>
        public static string Skills_SkillEnergyBoost {
            get {
                return ResourceManager.GetString("Skills_SkillEnergyBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquette.
        /// </summary>
        public static string Skills_SkillEtiquette {
            get {
                return ResourceManager.GetString("Skills_SkillEtiquette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Blow a Hit.
        /// </summary>
        public static string Skills_SkillEveryBlowAHit {
            get {
                return ResourceManager.GetString("Skills_SkillEveryBlowAHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feint.
        /// </summary>
        public static string Skills_SkillFeint {
            get {
                return ResourceManager.GetString("Skills_SkillFeint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fencing.
        /// </summary>
        public static string Skills_SkillFencing {
            get {
                return ResourceManager.GetString("Skills_SkillFencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flirting.
        /// </summary>
        public static string Skills_SkillFlirting {
            get {
                return ResourceManager.GetString("Skills_SkillFlirting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Damage.
        /// </summary>
        public static string Skills_SkillFullDamage {
            get {
                return ResourceManager.GetString("Skills_SkillFullDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Market.
        /// </summary>
        public static string Skills_SkillFutureMarket {
            get {
                return ResourceManager.GetString("Skills_SkillFutureMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        public static string Skills_SkillGambling {
            get {
                return ResourceManager.GetString("Skills_SkillGambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard to Kill.
        /// </summary>
        public static string Skills_SkillHardToKill {
            get {
                return ResourceManager.GetString("Skills_SkillHardToKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot.
        /// </summary>
        public static string Skills_SkillHeadshot {
            get {
                return ResourceManager.GetString("Skills_SkillHeadshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        public static string Skills_SkillHealing {
            get {
                return ResourceManager.GetString("Skills_SkillHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Fighting.
        /// </summary>
        public static string Skills_SkillHeavyFighting {
            get {
                return ResourceManager.GetString("Skills_SkillHeavyFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Parade.
        /// </summary>
        public static string Skills_SkillHeavyParade {
            get {
                return ResourceManager.GetString("Skills_SkillHeavyParade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijacker.
        /// </summary>
        public static string Skills_SkillHijackerMelee {
            get {
                return ResourceManager.GetString("Skills_SkillHijackerMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijacker.
        /// </summary>
        public static string Skills_SkillHijackerRanged {
            get {
                return ResourceManager.GetString("Skills_SkillHijackerRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter&apos;s Mark.
        /// </summary>
        public static string Skills_SkillHuntersMark {
            get {
                return ResourceManager.GetString("Skills_SkillHuntersMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidate.
        /// </summary>
        public static string Skills_SkillIntimidate {
            get {
                return ResourceManager.GetString("Skills_SkillIntimidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Attack.
        /// </summary>
        public static string Skills_SkillJumpAttack {
            get {
                return ResourceManager.GetString("Skills_SkillJumpAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string Skills_SkillKick {
            get {
                return ResourceManager.GetString("Skills_SkillKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing Spree.
        /// </summary>
        public static string Skills_SkillKillingSpree {
            get {
                return ResourceManager.GetString("Skills_SkillKillingSpree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge of People.
        /// </summary>
        public static string Skills_SkillKnowledgeOfPeople {
            get {
                return ResourceManager.GetString("Skills_SkillKnowledgeOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Breath.
        /// </summary>
        public static string Skills_SkillLastBreath {
            get {
                return ResourceManager.GetString("Skills_SkillLastBreath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Shot.
        /// </summary>
        public static string Skills_SkillLastShot {
            get {
                return ResourceManager.GetString("Skills_SkillLastShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lie Detector.
        /// </summary>
        public static string Skills_SkillLieDetector {
            get {
                return ResourceManager.GetString("Skills_SkillLieDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blow.
        /// </summary>
        public static string Skills_SkillLightBlow {
            get {
                return ResourceManager.GetString("Skills_SkillLightBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Shot.
        /// </summary>
        public static string Skills_SkillLightShot {
            get {
                return ResourceManager.GetString("Skills_SkillLightShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockpicking.
        /// </summary>
        public static string Skills_SkillLockpicking {
            get {
                return ResourceManager.GetString("Skills_SkillLockpicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lone Warrior.
        /// </summary>
        public static string Skills_SkillLoneWarrior {
            get {
                return ResourceManager.GetString("Skills_SkillLoneWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck.
        /// </summary>
        public static string Skills_SkillLuck {
            get {
                return ResourceManager.GetString("Skills_SkillLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Shot.
        /// </summary>
        public static string Skills_SkillLuckyShot {
            get {
                return ResourceManager.GetString("Skills_SkillLuckyShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine.
        /// </summary>
        public static string Skills_SkillMagazine {
            get {
                return ResourceManager.GetString("Skills_SkillMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterful Archer.
        /// </summary>
        public static string Skills_SkillMasterfulArcher {
            get {
                return ResourceManager.GetString("Skills_SkillMasterfulArcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master of Throwing Weapons.
        /// </summary>
        public static string Skills_SkillMasterOfThrowingWeapons {
            get {
                return ResourceManager.GetString("Skills_SkillMasterOfThrowingWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentum.
        /// </summary>
        public static string Skills_SkillMomentum {
            get {
                return ResourceManager.GetString("Skills_SkillMomentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail Down.
        /// </summary>
        public static string Skills_SkillNailDown {
            get {
                return ResourceManager.GetString("Skills_SkillNailDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature Study.
        /// </summary>
        public static string Skills_SkillNatureStudy {
            get {
                return ResourceManager.GetString("Skills_SkillNatureStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimble.
        /// </summary>
        public static string Skills_SkillNimble {
            get {
                return ResourceManager.GetString("Skills_SkillNimble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed Fighting.
        /// </summary>
        public static string Skills_SkillOneHandedFighting {
            get {
                return ResourceManager.GetString("Skills_SkillOneHandedFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oneshot.
        /// </summary>
        public static string Skills_SkillOneshot {
            get {
                return ResourceManager.GetString("Skills_SkillOneshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parad.
        /// </summary>
        public static string Skills_SkillParade {
            get {
                return ResourceManager.GetString("Skills_SkillParade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Block.
        /// </summary>
        public static string Skills_SkillPerfectBlock {
            get {
                return ResourceManager.GetString("Skills_SkillPerfectBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Blow.
        /// </summary>
        public static string Skills_SkillPerfectBlow {
            get {
                return ResourceManager.GetString("Skills_SkillPerfectBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Shot.
        /// </summary>
        public static string Skills_SkillPerfectShot {
            get {
                return ResourceManager.GetString("Skills_SkillPerfectShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perseverence.
        /// </summary>
        public static string Skills_SkillPerseverence {
            get {
                return ResourceManager.GetString("Skills_SkillPerseverence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercing Arrow.
        /// </summary>
        public static string Skills_SkillPiercingArrow {
            get {
                return ResourceManager.GetString("Skills_SkillPiercingArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plunge.
        /// </summary>
        public static string Skills_SkillPlunge {
            get {
                return ResourceManager.GetString("Skills_SkillPlunge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Knowledge.
        /// </summary>
        public static string Skills_SkillPoisonKnowledge {
            get {
                return ResourceManager.GetString("Skills_SkillPoisonKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise Throw.
        /// </summary>
        public static string Skills_SkillPreciseThrow {
            get {
                return ResourceManager.GetString("Skills_SkillPreciseThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Slingshot Marksman.
        /// </summary>
        public static string Skills_SkillProfessionalSlingshotMarksman {
            get {
                return ResourceManager.GetString("Skills_SkillProfessionalSlingshotMarksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Aim.
        /// </summary>
        public static string Skills_SkillQuickAim {
            get {
                return ResourceManager.GetString("Skills_SkillQuickAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickDraw.
        /// </summary>
        public static string Skills_SkillQuickdraw {
            get {
                return ResourceManager.GetString("Skills_SkillQuickdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Parade.
        /// </summary>
        public static string Skills_SkillQuickParade {
            get {
                return ResourceManager.GetString("Skills_SkillQuickParade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readiness.
        /// </summary>
        public static string Skills_SkillReadiness {
            get {
                return ResourceManager.GetString("Skills_SkillReadiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reckless Attack.
        /// </summary>
        public static string Skills_SkillRecklessAttack {
            get {
                return ResourceManager.GetString("Skills_SkillRecklessAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize Style.
        /// </summary>
        public static string Skills_SkillRecognizeStyle {
            get {
                return ResourceManager.GetString("Skills_SkillRecognizeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue is near.
        /// </summary>
        public static string Skills_SkillRescueIsNear {
            get {
                return ResourceManager.GetString("Skills_SkillRescueIsNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Skills_SkillReturn {
            get {
                return ResourceManager.GetString("Skills_SkillReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riposte.
        /// </summary>
        public static string Skills_SkillRiposte {
            get {
                return ResourceManager.GetString("Skills_SkillRiposte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round-House Attack.
        /// </summary>
        public static string Skills_SkillRoundHouseAttack {
            get {
                return ResourceManager.GetString("Skills_SkillRoundHouseAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routined with Throwing Weapons.
        /// </summary>
        public static string Skills_SkillRoutinedWithThrowingWeapons {
            get {
                return ResourceManager.GetString("Skills_SkillRoutinedWithThrowingWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Over.
        /// </summary>
        public static string Skills_SkillRunOver {
            get {
                return ResourceManager.GetString("Skills_SkillRunOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Hand.
        /// </summary>
        public static string Skills_SkillSecondHand {
            get {
                return ResourceManager.GetString("Skills_SkillSecondHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string Skills_SkillShield {
            get {
                return ResourceManager.GetString("Skills_SkillShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Bash.
        /// </summary>
        public static string Skills_SkillShieldBash {
            get {
                return ResourceManager.GetString("Skills_SkillShieldBash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Breaker.
        /// </summary>
        public static string Skills_SkillShieldBreaker {
            get {
                return ResourceManager.GetString("Skills_SkillShieldBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot from the Saddle.
        /// </summary>
        public static string Skills_SkillShootFromTheSaddle {
            get {
                return ResourceManager.GetString("Skills_SkillShootFromTheSaddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled Lier.
        /// </summary>
        public static string Skills_SkillSkilledLier {
            get {
                return ResourceManager.GetString("Skills_SkillSkilledLier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled Speaker.
        /// </summary>
        public static string Skills_SkillSkilledSpeaker {
            get {
                return ResourceManager.GetString("Skills_SkillSkilledSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled with Throwing Weapons.
        /// </summary>
        public static string Skills_SkillSkilledWithThrowingWeapons {
            get {
                return ResourceManager.GetString("Skills_SkillSkilledWithThrowingWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillful Retreat.
        /// </summary>
        public static string Skills_SkillSkillfulRetreat {
            get {
                return ResourceManager.GetString("Skills_SkillSkillfulRetreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slingshot Marksman.
        /// </summary>
        public static string Skills_SkillSlingshotMarksman {
            get {
                return ResourceManager.GetString("Skills_SkillSlingshotMarksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smithing.
        /// </summary>
        public static string Skills_SkillSmithing {
            get {
                return ResourceManager.GetString("Skills_SkillSmithing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneaking.
        /// </summary>
        public static string Skills_SkillSneaking {
            get {
                return ResourceManager.GetString("Skills_SkillSneaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something with Shield.
        /// </summary>
        public static string Skills_SkillSomethingWithShield {
            get {
                return ResourceManager.GetString("Skills_SkillSomethingWithShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Arrows.
        /// </summary>
        public static string Skills_SkillStrongArrows {
            get {
                return ResourceManager.GetString("Skills_SkillStrongArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Throw.
        /// </summary>
        public static string Skills_SkillStrongThrow {
            get {
                return ResourceManager.GetString("Skills_SkillStrongThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise Attack.
        /// </summary>
        public static string Skills_SkillSurpriseAttack {
            get {
                return ResourceManager.GetString("Skills_SkillSurpriseAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sympathic.
        /// </summary>
        public static string Skills_SkillSympathic {
            get {
                return ResourceManager.GetString("Skills_SkillSympathic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Hit.
        /// </summary>
        public static string Skills_SkillTakeAHit {
            get {
                return ResourceManager.GetString("Skills_SkillTakeAHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taunt.
        /// </summary>
        public static string Skills_SkillTaunt {
            get {
                return ResourceManager.GetString("Skills_SkillTaunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Skills_SkillTeacher {
            get {
                return ResourceManager.GetString("Skills_SkillTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theft.
        /// </summary>
        public static string Skills_SkillTheft {
            get {
                return ResourceManager.GetString("Skills_SkillTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There and Away.
        /// </summary>
        public static string Skills_SkillThereAndAway {
            get {
                return ResourceManager.GetString("Skills_SkillThereAndAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Skills_SkillTracking {
            get {
                return ResourceManager.GetString("Skills_SkillTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading.
        /// </summary>
        public static string Skills_SkillTrading {
            get {
                return ResourceManager.GetString("Skills_SkillTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Tree.
        /// </summary>
        public static string Skills_SkillTree {
            get {
                return ResourceManager.GetString("Skills_SkillTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trueshot.
        /// </summary>
        public static string Skills_SkillTrueshot {
            get {
                return ResourceManager.GetString("Skills_SkillTrueshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtually Invisible.
        /// </summary>
        public static string Skills_SkillVirtuallyInvisible {
            get {
                return ResourceManager.GetString("Skills_SkillVirtuallyInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons and Armor.
        /// </summary>
        public static string Skills_SkillWeaponsAndArmor {
            get {
                return ResourceManager.GetString("Skills_SkillWeaponsAndArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character loaded from.
        /// </summary>
        public static string Snackbar_CharacterLoaded {
            get {
                return ResourceManager.GetString("Snackbar_CharacterLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character created!.
        /// </summary>
        public static string Snackbar_CharacterNew {
            get {
                return ResourceManager.GetString("Snackbar_CharacterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character saved to.
        /// </summary>
        public static string Snackbar_CharacterSaved {
            get {
                return ResourceManager.GetString("Snackbar_CharacterSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value copied to Clipboard.
        /// </summary>
        public static string Snackbar_CopyToClipboard {
            get {
                return ResourceManager.GetString("Snackbar_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add Image.
        /// </summary>
        public static string Tooltip_AddImage {
            get {
                return ResourceManager.GetString("Tooltip_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Tooltip_CopyToClipboard {
            get {
                return ResourceManager.GetString("Tooltip_CopyToClipboard", resourceCulture);
            }
        }
    }
}
